### ISSUE TITLE
Cannot read properties of undefined (reading 'compiled')

### ISSUE THREAD

**Issue by salemgolemugoo** [concon121/serverless-plugin-aws-resource-names#11]
Using a simple config:
```
plugins:
  - serverless-aws-resource-names

custom:
  serverless-aws-resource-names:
    source: mapping.json
```

with mapping.json:
```
{
    "stack": "$service"
}
```

Receiving this error message:
```
Running "serverless" from node_modules
Setting custom naming conventions...
Setting custom function names...

Deploying simple to stage dev (us-east-1)

✖ Stack simple failed to deploy (0s)
Environment: darwin, node 20.4.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "nonprod-ilm" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'compiled')
    at Object.getCompiledTemplateFileName (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless-aws-resource-names/naming.js:30:44)
    at AwsPackage.saveCompiledTemplate (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/plugins/aws/package/lib/save-compiled-template.js:8:59)
    at aws:package:finalize:saveServiceState (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/plugins/aws/package/index.js:118:20)
    at PluginManager.runHooks (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:564:20)
    at async PluginManager.spawn (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async PluginManager.runHooks (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:564:9)
    at async PluginManager.spawn (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/plugins/deploy.js:48:11)
    at async PluginManager.runHooks (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/salem/Work/Oddity/repos/serverless-templates/node_modules/serverless/scripts/serverless.js:819:9
```

**Comment by salemgolemugoo** [comment]
Forgot to include 
```
    "template": {
        "compiled": "cloudformation-template-update-stack.json",
        "core": "cloudformation-template-create-stack.json"
    },
```
in the mapping.json
