### ISSUE TITLE
Using custom IAM role causes TypeError: Cannot read property 'Properties' of undefined

### ISSUE THREAD

**Issue by eballetbaz** [concon121/serverless-plugin-aws-resource-names#5]
When using a custom IAM role in serverless.yml it causes a "TypeError: Cannot read property 'Properties' of undefined"

Sample conf:

```
provider:
  name: aws
  region: eu-west-1
  role: arn:aws:iam::0123456789:role/roleInMyAccount
```

Full error stack

```
 TypeError: Cannot read property 'Properties' of undefined
     at AWSNaming.fixLogGroups (C:\xxx\node_modules\serverless-aws-resource-names\naming.js:78:33)
     at C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:498:55
     at tryCatcher (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
     at Object.gotValue (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:168:18)
     at Object.gotAccum (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:155:25)
     at Object.tryCatcher (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
     at Promise._settlePromiseFromHandler (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:547:31)
     at Promise._settlePromise (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:604:18)
     at Promise._settlePromise0 (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:649:10)
     at Promise._settlePromises (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:729:18)
     at _drainQueueStep (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:93:12)
     at _drainQueue (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:86:9)
     at Async._drainQueues (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:102:5)
     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\eballet-baz\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:15:14)
```

**Comment by concon121** [comment]
Merged and published a new version, thanks for contributing!
